# Generated by Django 5.1.6 on 2025-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_brand_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial',
            field=models.CharField(default='', max_length=9, unique=True, verbose_name='Número de Série'),
        ),
    ]
