# Generated by Django 5.1.6 on 2025-02-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_brand_category_created_at_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
