# Generated by Django 5.1.6 on 2025-02-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_brand_description_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
    ]
