# Generated by Django 5.1.6 on 2025-03-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_registeruser_remove_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentstatus',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Alteração'),
        ),
        migrations.AlterField(
            model_name='equipmentstatus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.registerproduct', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='equipmentstatus',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('in_use', 'Em Uso'), ('maintenance', 'Em Manutenção'), ('retired', 'Aposentado')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(verbose_name='Data da Manuteção'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='performed_by',
            field=models.CharField(max_length=255, verbose_name='Responśavel pela Manuteção'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.registerproduct', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída')], max_length=10, verbose_name='Entrada Tipo'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.registerproduct', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='responsible_person',
            field=models.CharField(max_length=255, verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='fullname',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
    ]
