# Generated by Django 5.1.6 on 2025-03-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_equipmentstatus_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentstatus',
            options={'ordering': ['product'], 'verbose_name': 'Status Equipamento'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['product'], 'verbose_name': 'Manutenção'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['product'], 'verbose_name': 'Entrada e Saida'},
        ),
    ]
