# Generated by Django 5.1.6 on 2025-03-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_equipmentstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeruser',
            options={'ordering': ['fullname'], 'verbose_name': 'Usuários'},
        ),
    ]
