# Generated by Django 5.1.6 on 2025-03-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_registeruser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeruser',
            options={'ordering': ['fullname'], 'verbose_name': 'Usuário'},
        ),
    ]
