# Generated by Django 5.1.6 on 2025-03-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_registeruser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='cpf',
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Senha'),
        ),
    ]
