# Generated by Django 5.1.6 on 2025-03-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_registerproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerproduct',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
