# Generated by Django 5.1.6 on 2025-03-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_registerproduct_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerproduct',
            name='serial_number',
            field=models.CharField(max_length=9),
        ),
    ]
