# Generated by Django 5.1.6 on 2025-03-21 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_movement_options_remove_movement_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='product',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='register_product',
        ),
        migrations.AlterModelOptions(
            name='registeruser',
            options={'ordering': ['fullname'], 'verbose_name': 'Registrar Usuário'},
        ),
        migrations.RemoveField(
            model_name='registerproduct',
            name='status_product',
        ),
        migrations.RemoveField(
            model_name='registerproduct',
            name='type',
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='date_aquisition',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data - Entrada'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome - Produto'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='serial_number',
            field=models.CharField(max_length=9, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor'),
        ),
        migrations.DeleteModel(
            name='EquipmentStatus',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
