# Generated by Django 5.1.6 on 2025-03-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_registerproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerproduct',
            name='serial_number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Serial'),
        ),
    ]
