# Generated by Django 5.1.6 on 2025-03-21 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_registerproduct_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='registerproduct',
            name='supplier',
        ),
        migrations.AddField(
            model_name='registerproduct',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='registerproduct',
            name='allocator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alocador'),
        ),
        migrations.AddField(
            model_name='registerproduct',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data - Final'),
        ),
        migrations.AddField(
            model_name='registerproduct',
            name='leased',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Locador'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='date_aquisition',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data - Inicial'),
        ),
    ]
