# Generated by Django 5.1.6 on 2025-03-26 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_registerproduct_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('inventory', 'Inventário por Departamento'), ('maintenance', 'Histórico de Manutenções'), ('movements', 'Movimentações de Equipamentos'), ('costs', 'Análise de Custos'), ('performance', 'Performance de Equipamentos')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('file', models.FileField(upload_to='reports/')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.registeruser')),
            ],
        ),
    ]
