# Generated by Django 5.1.6 on 2025-03-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
